package db

import (
	"github.com/idena-network/idena-go/common/hexutil"
	"github.com/idena-network/idena-indexer-api/app/types"
	"github.com/shopspring/decimal"
	"time"
)

type Accessor interface {
	Search(value string) ([]types.Entity, error)

	Coins() (types.AllCoins, error)
	CirculatingSupply(addressesToExclude []string) (decimal.Decimal, error)
	ActiveAddressesCount(afterTime time.Time) (uint64, error)

	Upgrades(count uint64, continuationToken *string) ([]types.ActivatedUpgrade, *string, error)
	UpgradeVotings(count uint64, continuationToken *string) ([]types.Upgrade, *string, error)
	UpgradeVotingHistory(upgrade uint64) ([]*types.UpgradeVotingHistoryItem, error)
	Upgrade(upgrade uint64) (*types.Upgrade, error)

	EpochsCount() (uint64, error)
	Epochs(count uint64, continuationToken *string) ([]types.EpochSummary, *string, error)

	LastEpoch() (types.EpochDetail, error)
	Epoch(epoch uint64) (types.EpochDetail, error)
	EpochBlocksCount(epoch uint64) (uint64, error)
	EpochBlocks(epoch uint64, count uint64, continuationToken *string) ([]types.BlockSummary, *string, error)
	EpochFlipsCount(epoch uint64) (uint64, error)
	EpochFlips(epoch uint64, count uint64, continuationToken *string) ([]types.FlipSummary, *string, error)
	EpochFlipAnswersSummary(epoch uint64) ([]types.StrValueCount, error)
	EpochFlipStatesSummary(epoch uint64) ([]types.StrValueCount, error)
	EpochFlipWrongWordsSummary(epoch uint64) ([]types.NullableBoolValueCount, error)
	EpochIdentitiesCount(epoch uint64, prevStates []string, states []string) (uint64, error)
	EpochIdentities(epoch uint64, prevStates []string, states []string, count uint64,
		continuationToken *string) ([]types.EpochIdentity, *string, error)
	EpochIdentityStatesSummary(epoch uint64) ([]types.StrValueCount, error)
	EpochIdentityStatesInterimSummary(epoch uint64) ([]types.StrValueCount, error)
	EpochInvitesSummary(epoch uint64) (types.InvitesSummary, error)
	EpochInviteStatesSummary(epoch uint64) ([]types.StrValueCount, error)
	EpochInvitesCount(epoch uint64) (uint64, error)
	EpochInvites(epoch uint64, count uint64, continuationToken *string) ([]types.Invite, *string, error)
	EpochTxsCount(epoch uint64) (uint64, error)
	EpochTxs(epoch uint64, count uint64, continuationToken *string) ([]types.TransactionSummary, *string, error)
	EpochCoins(epoch uint64) (types.AllCoins, error)
	EpochRewardsSummary(epoch uint64) (types.RewardsSummary, error)
	EpochBadAuthorsCount(epoch uint64) (uint64, error)
	EpochBadAuthors(epoch uint64, count uint64, continuationToken *string) ([]types.BadAuthor, *string, error)
	EpochIdentitiesRewardsCount(epoch uint64) (uint64, error)
	EpochIdentitiesRewards(epoch uint64, count uint64, continuationToken *string) ([]types.Rewards, *string, error)
	EpochFundPayments(epoch uint64) ([]types.FundPayment, error)
	EpochRewardBounds(epoch uint64) ([]types.RewardBounds, error)
	EpochDelegateeTotalRewards(epoch uint64, count uint64, continuationToken *string) ([]types.DelegateeTotalRewards, *string, error)

	EpochIdentity(epoch uint64, address string) (types.EpochIdentity, error)
	EpochIdentityShortFlipsToSolve(epoch uint64, address string) ([]string, error)
	EpochIdentityLongFlipsToSolve(epoch uint64, address string) ([]string, error)
	EpochIdentityShortAnswers(epoch uint64, address string) ([]types.Answer, error)
	EpochIdentityLongAnswers(epoch uint64, address string) ([]types.Answer, error)
	EpochIdentityFlips(epoch uint64, address string) ([]types.FlipSummary, error)
	EpochIdentityFlipsWithRewardFlag(epoch uint64, address string) ([]types.FlipWithRewardFlag, error)
	EpochIdentityReportedFlipRewards(epoch uint64, address string) ([]types.ReportedFlipReward, error)
	EpochIdentityRewards(epoch uint64, address string) ([]types.Reward, error)
	EpochIdentityBadAuthor(epoch uint64, address string) (*types.BadAuthor, error)
	EpochIdentityInvitesWithRewardFlag(epoch uint64, address string) ([]types.InviteWithRewardFlag, error)
	EpochIdentitySavedInviteRewards(epoch uint64, address string) ([]types.StrValueCount, error)
	EpochIdentityAvailableInvites(epoch uint64, address string) ([]types.EpochInvites, error)
	EpochDelegateeRewards(epoch uint64, address string, count uint64, continuationToken *string) ([]types.DelegateeReward, *string, error)
	EpochIdentityValidationSummary(epoch uint64, address string) (types.ValidationSummary, error)
	EpochAddressDelegateeTotalRewards(epoch uint64, address string) (types.DelegateeTotalRewards, error)

	BlockByHeight(height uint64) (types.BlockDetail, error)
	BlockTxsCountByHeight(height uint64) (uint64, error)
	BlockTxsByHeight(height uint64, count uint64, continuationToken *string) ([]types.TransactionSummary, *string, error)
	BlockByHash(hash string) (types.BlockDetail, error)
	BlockTxsCountByHash(hash string) (uint64, error)
	BlockTxsByHash(hash string, count uint64, continuationToken *string) ([]types.TransactionSummary, *string, error)
	BlockCoinsByHeight(height uint64) (types.AllCoins, error)
	BlockCoinsByHash(hash string) (types.AllCoins, error)
	LastBlock() (types.BlockDetail, error)

	Flip(hash string) (types.Flip, error)
	FlipContent(hash string) (types.FlipContent, error)
	FlipAnswers(hash string, isShort bool) ([]types.Answer, error)
	FlipEpochAdjacentFlips(hash string) (types.AdjacentStrValues, error)

	Identity(address string) (types.Identity, error)
	IdentityAge(address string) (uint64, error)
	IdentityCurrentFlipCids(address string) ([]string, error)
	IdentityEpochsCount(address string) (uint64, error)
	IdentityEpochs(address string, count uint64, continuationToken *string) ([]types.EpochIdentity, *string, error)
	IdentityFlipsCount(address string) (uint64, error)
	IdentityFlips(address string, count uint64, continuationToken *string) ([]types.FlipSummary, *string, error)
	IdentityFlipQualifiedAnswers(address string) ([]types.StrValueCount, error)
	IdentityFlipStates(address string) ([]types.StrValueCount, error)
	IdentityInvitesCount(address string) (uint64, error)
	IdentityInvites(address string, count uint64, continuationToken *string) ([]types.Invite, *string, error)
	IdentityTxsCount(address string) (uint64, error)
	IdentityTxs(address string, count uint64, continuationToken *string) ([]types.TransactionSummary, *string, error)
	IdentityRewardsCount(address string) (uint64, error)
	IdentityRewards(address string, count uint64, continuationToken *string) ([]types.Reward, *string, error)
	IdentityEpochRewardsCount(address string) (uint64, error)
	IdentityEpochRewards(address string, count uint64, continuationToken *string) ([]types.Rewards, *string, error)

	Address(address string) (types.Address, error)
	AddressPenaltiesCount(address string) (uint64, error)
	AddressPenalties(address string, count uint64, continuationToken *string) ([]types.Penalty, *string, error)
	AddressStatesCount(address string) (uint64, error)
	AddressStates(address string, count uint64, continuationToken *string) ([]types.AddressState, *string, error)
	AddressTotalLatestMiningReward(afterTime time.Time, address string) (types.TotalMiningReward, error)
	AddressTotalLatestBurntCoins(afterTime time.Time, address string) (types.AddressBurntCoins, error)
	AddressBadAuthorsCount(address string) (uint64, error)
	AddressBadAuthors(address string, count uint64, continuationToken *string) ([]types.BadAuthor, *string, error)
	AddressBalanceUpdatesCount(address string) (uint64, error)
	AddressBalanceUpdates(address string, count uint64, continuationToken *string) ([]types.BalanceUpdate, *string, error)
	AddressBalanceUpdatesSummary(address string) (*types.BalanceUpdatesSummary, error)
	AddressContractTxBalanceUpdates(address string, contractAddress string, count uint64, continuationToken *string) ([]types.ContractTxBalanceUpdate, *string, error)
	AddressDelegateeTotalRewards(address string, count uint64, continuationToken *string) ([]types.DelegateeTotalRewards, *string, error)
	AddressMiningRewardSummaries(address string, count uint64, continuationToken *string) ([]types.MiningRewardSummary, *string, error)

	Transaction(hash string) (*types.TransactionDetail, error)
	TransactionRaw(hash string) (*hexutil.Bytes, error)

	BalancesCount() (uint64, error)
	Balances(sortBy *string, count uint64, continuationToken *string) ([]types.Balance, *string, error)

	TotalLatestMiningRewardsCount(afterTime time.Time) (uint64, error)
	TotalLatestMiningRewards(afterTime time.Time, startIndex uint64, count uint64) ([]types.TotalMiningReward, error)
	TotalLatestBurntCoinsCount(afterTime time.Time) (uint64, error)
	TotalLatestBurntCoins(afterTime time.Time, startIndex uint64, count uint64) ([]types.AddressBurntCoins, error)

	Contract(address string) (types.Contract, error)
	ContractTxBalanceUpdates(contractAddress string, count uint64, continuationToken *string) ([]types.ContractTxBalanceUpdate, *string, error)

	TimeLockContract(address string) (types.TimeLockContract, error)
	OracleLockContract(address string) (types.OracleLockContract, error)
	RefundableOracleLockContract(address string) (types.RefundableOracleLockContract, error)
	MultisigContract(address string) (types.MultisigContract, error)

	OracleVotingContracts(authorAddress, oracleAddress string, states []string, all bool, sortBy *string, count uint64, continuationToken *string) ([]types.OracleVotingContract, *string, error)
	AddressOracleVotingContracts(address string, count uint64, continuationToken *string) ([]types.OracleVotingContract, *string, error)
	OracleVotingContract(address, oracle string) (types.OracleVotingContract, error)
	EstimatedOracleRewards() ([]types.EstimatedOracleReward, error)

	PoolsCount() (uint64, error)
	Pools(count uint64, continuationToken *string) ([]*types.Pool, *string, error)
	Pool(address string) (*types.Pool, error)
	PoolDelegatorsCount(address string) (uint64, error)
	PoolDelegators(address string, count uint64, continuationToken *string) ([]*types.Delegator, *string, error)

	MinersHistory() ([]types.MinersHistoryItem, error)
	PeersHistory(count uint64) ([]types.PeersHistoryItem, error)

	DynamicEndpoints() ([]types.DynamicEndpoint, error)
	DynamicEndpointData(dataSource string, limit *int) (*types.DynamicEndpointResult, error)

	Destroy()
}
